services:
  ml-notebook:
    build: .
    container_name: telco-ml-lab
    ports:
      - "8888:8888"
      - "8501:8501"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_NOTEBOOK_DIR=/home/jovyan/telco-poc/notebooks
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    working_dir: /home/jovyan
    volumes:
      - .:/home/jovyan/telco-poc
      - ${DATA_PATH}:/home/jovyan/data

volumes: {}
